name = "Gadfly"
uuid = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
version = "1.2.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
CoupledFields = "7ad07ef1-bdf2-5661-9d2b-286fd4296dac"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Hexagons = "a1b4810d-1bce-5fbd-ac56-80944d57a21f"
IndirectArrays = "9b13fd28-a010-5f03-acff-a1bbcff69959"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Juno = "e5e0dc1b-0480-54bc-9374-aad01c23163d"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Loess = "4345ca2d-374a-55d4-8d30-97f9976e7612"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Showoff = "992d4aef-0814-514b-bc4d-f2e9a6c4116f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Cairo = "0.7, 0.8"
CategoricalArrays = "0.5, 0.6, 0.7"
Colors = "0.9, 0.10, 0.11, 0.12"
Compose = "0.7, 0.8"
Contour = "0.5"
CoupledFields = "0.1"
DataFrames = "0.15, 0.16, 0.17, 0.18, 0.19, 0.20"
DataStructures = "0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17"
Distributions = "0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22"
DocStringExtensions = "0.7, 0.8"
Hexagons = "0.2"
IndirectArrays = "0.5"
IterTools = "1"
JSON = "0.18, 0.19, 0.20, 0.21"
Juno = "0.7, 0.8"
KernelDensity = "0.5"
Loess = "0.4, 0.5"
Measures = "0.3"
RDatasets = "0.6"
Requires = "0.5, 1.0"
Showoff = "0.2, 0.3"
Unitful = "0.15, 0.16"
julia = "1"

[extras]
Cairo = "159f3aea-2a34-519c-b102-8c37f9878175"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Cairo", "DataFrames", "DelimitedFiles", "LibGit2", "RDatasets", "Test", "Unitful"]
